qnd41_app_stg/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

qnd41_app_stg/sbacart/urls.py
from django.urls import path
from . import views

app_name = 'sbacart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

qnd41_app_stg/sbaorders/urls.py
from django.urls import path
from . import views

app_name = 'sbaorders'

urlpatterns = [
    path('sbacreate/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

qnd41_app_stg/sbashop/urls.py
from django.urls import path
from . import views

app_name = 'sbashop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

qnd41_app_stg/sblcart/urls.py
from django.urls import path
from . import views

app_name = 'sblcart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

qnd41_app_stg/sbacart/models.py
from django.db import models

# Create your models here.

qnd41_app_stg/sbacart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

qnd41_app_stg/sbacart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from sbashop.models import SBAProduct
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(SBAProduct, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('sbacart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(SBAProduct, id=product_id)
    cart.remove(product)
    return redirect('sbacart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                              initial={'quantity': item['quantity'],
                              'update': True})
    return render(request, 'sbacart/detail.html', {'cart': cart})

qnd41_app_stg/sbacart/templates/sbacart/detail.html
{% extends "sbashop/base.html" %}
{% load i18n wagtailcore_tags wagtailimages_tags %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
{% include 'shop/header.html' %}

<section class="pt-50 pb-50 dark-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
       
      </div>
      <div class="col-md-1"></div>
   
    </div>
  </div>
</section>

<section>
  
  <div class="container">
    <div class="row">
      <div class="col-md-12 terms">
        <h2 class="font-700">{% trans 'Your SmartQuail shopping cart' %}</h2>
        <ul class="careers-listing">
          {% for item in cart %}
          {% with product=item.product %}
          <li>
           
            <div class="row">
              <div class="career-main col-md-6">
                <h5 class="font-700">{{product.name}}</h5>
                <span class="default-color career-type">{% trans 'Price' %}: ${{ item.price }}
                </span> <span class="career-location"><i class="icofont icofont-google-map-circle"></i>{% trans 'Description' %}: {{item.description}}</span> </div>
            
                <div class="col-md-3 career-category"><span>{% trans 'Subtotal price' %}: ${{ item.total_price }} </span></div>
              <div class="career-details col-md-3"> 
                <form action="{% url "sblcart:cart_add" product.id %}" method="post">
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.update }}
                  <input type="submit" class="btn btn-color btn-square btn-animate" value="Update">
                  {% csrf_token %}
                </form>  
                <a class="btn btn-dark btn-square btn-animate" href="{% url "sblcart:cart_remove" product.id %}">{% trans 'Remove' %}</a>   
            </div>
           
          </li>
          {% endwith %}
          {% endfor %}
        </ul>
        <h2 class="mt-80 font-700"> {% trans 'TOTAL PRICE'%}: ${{ cart.get_total_price }}</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget nisl gravida, interdum nunc quis, faucibus ligula. Nam eu neque nunc. Suspendisse egestas dolor ante, nec tincidunt sem malesuada at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi vehicula metus sit amet turpis malesuada commodo.</p>
      </div>
      <a href="{% url "sbashop:product_list" %}" class="btn btn-dark btn-square btn-animate">{% trans 'Continue shopping' %}</a>
      <a href="{% url "sbaorders:order_create" %}" class="btn btn-color btn-square btn-animate">
        {% trans 'Checkout' %}
      </a>
    </div>
  </div>
</section>


{% endblock %}